
package br.com.nfse.nfse_saas.nfse.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "nfse", targetNamespace = "http://nfse.abrasf.org.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Nfse {


    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelarNfse", action = "http://nfse.abrasf.org.br/CancelarNfse")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "CancelarNfse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "CancelarNfseResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String cancelarNfse(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarLoteRps", action = "http://nfse.abrasf.org.br/ConsultarLoteRps")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarLoteRps", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarLoteRpsResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarLoteRps(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfseServicoPrestado", action = "http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarNfseServicoPrestado", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarNfseServicoPrestadoResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarNfseServicoPrestado(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfseServicoTomado", action = "http://nfse.abrasf.org.br/ConsultarNfseServicoTomado")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarNfseServicoTomado", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarNfseServicoTomadoResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarNfseServicoTomado(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfsePorFaixa", action = "http://nfse.abrasf.org.br/ConsultarNfsePorFaixa")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarNfsePorFaixa", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarNfsePorFaixaResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarNfsePorFaixa(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfsePorRps", action = "http://nfse.abrasf.org.br/ConsultarNfsePorRps")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarNfsePorRps", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarNfsePorRpsResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarNfsePorRps(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecepcionarLoteRps", action = "http://nfse.abrasf.org.br/RecepcionarLoteRps")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "RecepcionarLoteRps", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "RecepcionarLoteRpsResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String recepcionarLoteRps(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GerarNfse", action = "http://nfse.abrasf.org.br/GerarNfse")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "GerarNfse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "GerarNfseResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String gerarNfse(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SubstituirNfse", action = "http://nfse.abrasf.org.br/SubstituirNfse")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "SubstituirNfse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "SubstituirNfseResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String substituirNfse(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecepcionarLoteRpsSincrono", action = "http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "RecepcionarLoteRpsSincrono", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "RecepcionarLoteRpsSincronoResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String recepcionarLoteRpsSincrono(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarUrlNfse", action = "http://nfse.abrasf.org.br/ConsultarUrlNfse")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarUrlNfse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarUrlNfseResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarUrlNfse(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarDadosCadastrais", action = "http://nfse.abrasf.org.br/ConsultarDadosCadastrais")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarDadosCadastrais", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarDadosCadastraisResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarDadosCadastrais(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseDadosMsg
     * @param nfseCabecMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarRpsDisponivel", action = "http://nfse.abrasf.org.br/ConsultarRpsDisponivel")
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarRpsDisponivel", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Input")
    @ResponseWrapper(localName = "ConsultarRpsDisponivelResponse", targetNamespace = "http://nfse.abrasf.org.br", className = "br.com.seu.erp.nfse.wsdl.Output")
    public String consultarRpsDisponivel(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

}

