ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'USER';

UPDATE usuario SET role = 'USER' WHERE role IS NULL;

ALTER TABLE usuario ALTER COLUMN role SET DEFAULT 'USER';
ALTER TABLE usuario ALTER COLUMN role SET NOT NULL;
