ALTER TABLE empresa
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS telefone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS logomarca_nome VARCHAR(255),
    ADD COLUMN IF NOT EXISTS logomarca_base64 TEXT;

ALTER TABLE endereco
    ADD COLUMN IF NOT EXISTS complemento VARCHAR(255),
    ADD COLUMN IF NOT EXISTS codigo_municipio_ibge VARCHAR(20),
    ADD COLUMN IF NOT EXISTS pais VARCHAR(100);